function args = defaultArgs()
%  args = defaultArgs()
%-----------------------------------------------------------------------------
%  Set the values of this function to those used for repeated analyses. This
% is reference by the object class rbm.m, if no input arguments are given
%-----------------------------------------------------------------------------
% DES

args = {'type', 'BB', ...
		'nHid', 50, ...
		'verbose', 1, ...
		'eta', 0.1, ...
		'momentum', 0.5, ...
		'nEpoch', 20, ...
		'wDecay', 0.002, ...
		'batchSz', 12, ...
		'anneal', 0, ...
		'nGibbs', 1, ...
		'varyEta',1};