function args = defaultDBN()
%  args = defaultDBN()
%-----------------------------------------------------------------------------
%  Set the values of this function to those used for a default DBN
%  object. This is reference by the object class rbmClassifier.m, if no input
%  arguments are given.
%-----------------------------------------------------------------------------
% DES

args = {'type','BB' , ...
		'nHid', [100, 200,200,10] ...
		'verbose', 1, ...
		'eta', [0.1,0.1,.1,.1] ...
		'momentum', 0.5, ...
		'nEpoch', [100,100,100,200] ...
		'wDecay', 0.0002, ...
		'batchSz', 10, ...
		'anneal', 1, ...
		'varyEta',[0,0,1,1], ...
		'classify',1, ...
		'nGibbs', 1};