function argOut = parseArgs(args,layer);

if nargin == 1 % JUST LOOKING FOR # HIDDEN UNITS
	for iA = 1:2:numel(args)
		if strcmp(args{iA},'nHid');
			argOut = numel(args{iA+1});
			break
		 end
	end

elseif nargin < 2
	error('parseArgs needs at least 2 arguments');
else
	if mod(numel(args),2)
		error('<args> must be a set of string-value pairs')
	end

	argOut = getDefaults();

	for iA = 1:2:numel(args)
		arg = args{iA}; val = args{iA+1};
		try
			if numel(val) > 1 & ~isstr(val)
				val = val(layer);
			end
			argOut{find(strcmp(arg,argOut))+1} = val;
		catch
			argOut{find(strcmp(arg,argOut))+1} = val(1);
		end
	end
end

function args = getDefaults()
args = {'type','BB', ...
		'nHid', 100, ...
		'eta', 0.1, ...
		'momentum', 0.5, ...
		'nEpoch', 100, ...
		'wDecay', 0.0002, ...
		'wPenalty', 0.0002, ...
		'anneal',  0, ...
		'batchSz',  100, ...
		'nGibbs',  1, ...
		'verbose', 1, ...
		'varyEta', 1, ...
		'classify',0, ...
		'bpCost','xent', ...
		'nFineTune',[], ...
		'learnSigma2',1};